
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: scanuser
      POSTGRES_PASSWORD: scanpass
      POSTGRES_DB: scandb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  scanner:
    build:
      context: .
      dockerfile: Dockerfile.scanner
    restart: always
    environment:
      FLASK_ENV: production
      PYTHONUNBUFFERED: 1
    ports:
      - "5001:5001"
    volumes:
      - .:/app
      - scanner-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  backend:
    build: .
    depends_on:
      - db
      - scanner
    environment:
      DATABASE_URL: postgres://scanuser:scanpass@db:5432/scandb
      SCANNER_API_URL: http://scanner:5001
      PORT: 5000
      NODE_ENV: production
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
  scanner-data:
