
services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: scanuser
      POSTGRES_PASSWORD: scanpass
      POSTGRES_DB: scandb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://scanuser:scanpass@db:5432/scandb
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
