thresholds:
  momentum_short: 0.02
  rsi_min: 48
  rsi_max: 68
  macd_min: 0.1
  weak: 0.02
  med: 0.04
  strong: 0.08
  high: 0.08
  low: 0.02
volatility:
  volumeRatio: 1.1
  atr: 1.3
  rv: 0.9
  ivPercentile: 75
