{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3cc63607",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name '__file__' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 15\u001b[39m\n\u001b[32m     11\u001b[39m \u001b[38;5;28;01mimport\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[34;01mos\u001b[39;00m\n\u001b[32m     13\u001b[39m \u001b[38;5;66;03m# Ensure `vfmd_system/src` is on sys.path so local modules can be imported\u001b[39;00m\n\u001b[32m     14\u001b[39m \u001b[38;5;66;03m# This allows running this notebook/script from the repository root or other CWDs\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m15\u001b[39m sys.path.insert(\u001b[32m0\u001b[39m, os.path.abspath(os.path.join(os.path.dirname(\u001b[34;43m__file__\u001b[39;49m), \u001b[33m'\u001b[39m\u001b[33m..\u001b[39m\u001b[33m'\u001b[39m, \u001b[33m'\u001b[39m\u001b[33msrc\u001b[39m\u001b[33m'\u001b[39m)))\n\u001b[32m     16\u001b[39m \u001b[38;5;66;03m# Debug: print resolved src path and start of sys.path for troubleshooting\u001b[39;00m\n\u001b[32m     17\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[31mNameError\u001b[39m: name '__file__' is not defined"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Phase 1 Validation Runner\n",
    "Complete script to validate VFMD physics engine\n",
    "\"\"\"\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import json\n",
    "import sys\n",
    "import os\n",
    "\n",
    "# Ensure `vfmd_system/src` is on sys.path so local modules can be imported\n",
    "# This allows running this notebook/script from the repository root or other CWDs\n",
    "# Try several candidate locations for the local `src` directory and insert the first that exists\n",
    "candidate_paths = [\n",
    "    os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')),\n",
    "    os.path.abspath(os.path.join(os.getcwd(), 'vfmd_system', 'src')),\n",
    "    os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))\n",
    "]\n",
    "\n",
    "inserted = False\n",
    "for p in candidate_paths:\n",
    "    if os.path.exists(p) and p not in sys.path:\n",
    "        sys.path.insert(0, p)\n",
    "        inserted = True\n",
    "        break\n",
    "\n",
    "# Debug: print resolved src path and start of sys.path for troubleshooting\n",
    "try:\n",
    "    print(f\"DEBUG: candidate_paths={candidate_paths}\")\n",
    "    print(f\"DEBUG: inserted={inserted}\")\n",
    "    print(f\"DEBUG: sys.path[0:5]={sys.path[0:5]}\")\n",
    "except Exception:\n",
    "    pass\n",
    "\n",
    "# Import our modules\n",
    "from data_fetcher import DataFetcher, DataPreprocessor\n",
    "from field_constructor import SimpleFieldConstructor, FieldAnalyzer\n",
    "from physics_calculator import PhysicsCalculator, ValidationEngine\n",
    "from visualizer import VFMDVisualizer\n",
    "\n",
    "\n",
    "def phase1_complete_validation():\n",
    "    \"\"\"\n",
    "    Run complete Phase 1 validation\n",
    "    This is your single entry point to validate everything\n",
    "    \"\"\"\n",
    "    \n",
    "    print(\"=\" * 70)\n",
    "    print(\"VFMD PHASE 1: CORE PHYSICS ENGINE VALIDATION\")\n",
    "    print(\"=\" * 70)\n",
    "    print()\n",
    "    \n",
    "    # ========== STEP 1: DATA ACQUISITION ==========\n",
    "    print(\"STEP 1: Fetching market data...\")\n",
    "    print(\"-\" * 70)\n",
    "    \n",
    "    try:\n",
    "        # Try to load existing data first\n",
    "        df = pd.read_csv('data/processed/btc_usdt_1m_processed.csv',\n",
    "                        index_col='timestamp', parse_dates=True)\n",
    "        print(f\"✅ Loaded existing data: {len(df)} bars\")\n",
    "        \n",
    "    except FileNotFoundError:\n",
    "        print(\"No existing data found. Fetching from exchange...\")\n",
    "        \n",
    "        fetcher = DataFetcher('binance')\n",
    "        df = fetcher.fetch_ohlcv(\n",
    "            symbol='BTC/USDT',\n",
    "            timeframe='1m',\n",
    "            days_back=180  # 6 months\n",
    "        )\n",
    "        \n",
    "        # Clean and prepare\n",
    "        preprocessor = DataPreprocessor()\n",
    "        df = preprocessor.clean_data(df)\n",
    "        df = preprocessor.add_features(df)\n",
    "        \n",
    "        # Save\n",
    "        df.to_csv('data/processed/btc_usdt_1m_processed.csv')\n",
    "        print(f\"✅ Fetched and saved: {len(df)} bars\")\n",
    "    \n",
    "    print(f\"Date range: {df.index[0]} to {df.index[-1]}\")\n",
    "    print()\n",
    "    \n",
    "    # ========== STEP 2: FIND VALIDATION EVENTS ==========\n",
    "    print(\"STEP 2: Identifying breakouts and chop zones...\")\n",
    "    print(\"-\" * 70)\n",
    "    \n",
    "    preprocessor = DataPreprocessor()\n",
    "    \n",
    "    breakouts = preprocessor.find_breakouts(df, lookback=20, threshold=0.02)\n",
    "    chop_zones = preprocessor.find_chop_zones(df, window=50, threshold=0.015)\n",
    "    \n",
    "    # Extract just the indices\n",
    "    breakout_indices = [b['index'] for b in breakouts]\n",
    "    chop_indices = [c['index'] for c in chop_zones]\n",
    "    \n",
    "    print(f\"✅ Found {len(breakouts)} breakouts\")\n",
    "    print(f\"✅ Found {len(chop_zones)} chop zones\")\n",
    "    print()\n",
    "    \n",
    "    # ========== STEP 3: BUILD SAMPLE FIELD ==========\n",
    "    print(\"STEP 3: Building sample vector field...\")\n",
    "    print(\"-\" * 70)\n",
    "    \n",
    "    constructor = SimpleFieldConstructor(\n",
    "        spatial_bins=50,\n",
    "        temporal_window=100,\n",
    "        smoothing_sigma=2.0\n",
    "    )\n",
    "    \n",
    "    # Build field from a sample period\n",
    "    sample_idx = len(df) // 2\n",
    "    sample_prices = df['close'].values[sample_idx-100:sample_idx]\n",
    "    \n",
    "    field = constructor.construct_field(sample_prices)\n",
    "    \n",
    "    print(f\"✅ Field constructed: shape {field.shape}\")\n",
    "    \n",
    "    # Calculate physics\n",
    "    metrics = PhysicsCalculator.compute_all_metrics(field)\n",
    "    \n",
    "    print(f\"   PEG: {metrics['peg']:.3f}\")\n",
    "    print(f\"   TI: {metrics['ti']:.3f}\")\n",
    "    print(f\"   Coherence: {metrics['coherence']:.3f}\")\n",
    "    print()\n",
    "    \n",
    "    # Visualize sample field\n",
    "    viz = VFMDVisualizer()\n",
    "    fig1 = viz.plot_field_with_price(field, sample_prices, \n",
    "                                     title=\"Sample Market Vector Field\")\n",
    "    fig1.savefig('validation_plots/sample_field.png', dpi=150, bbox_inches='tight')\n",
    "    print(\"✅ Saved: validation_plots/sample_field.png\")\n",
    "    plt.close(fig1)\n",
    "    print()\n",
    "    \n",
    "    # ========== STEP 4: VALIDATE PEG ON BREAKOUTS ==========\n",
    "    print(\"STEP 4: Validating PEG on historical breakouts...\")\n",
    "    print(\"-\" * 70)\n",
    "    \n",
    "    validator = ValidationEngine()\n",
    "    \n",
    "    peg_validation = validator.validate_peg_on_breakouts(\n",
    "        prices=df['close'].values,\n",
    "        breakout_indices=breakout_indices[:10],  # Test on first 10\n",
    "        lookback=20\n",
    "    )\n",
    "    \n",
    "    # Plot sample breakout\n",
    "    if peg_validation['details']:\n",
    "        sample_result = peg_validation['details'][0]\n",
    "        breakout_idx = sample_result['breakout_idx']\n",
    "        peg_timeline = sample_result['peg_timeline']\n",
    "        \n",
    "        # Rebuild field at breakout\n",
    "        breakout_prices = df['close'].values[breakout_idx-100:breakout_idx]\n",
    "        breakout_field = constructor.construct_field(breakout_prices)\n",
    "        \n",
    "        fig2 = viz.plot_sample_breakout_analysis(\n",
    "            df['close'].values,\n",
    "            breakout_field,\n",
    "            breakout_idx,\n",
    "            peg_timeline\n",
    "        )\n",
    "        fig2.savefig('validation_plots/breakout_analysis.png', dpi=150, bbox_inches='tight')\n",
    "        print(\"✅ Saved: validation_plots/breakout_analysis.png\")\n",
    "        plt.close(fig2)\n",
    "        \n",
    "        # Plot PEG timeline\n",
    "        fig3 = viz.plot_peg_timeline(peg_timeline, breakout_idx, lookback=20)\n",
    "        fig3.savefig('validation_plots/peg_timeline.png', dpi=150, bbox_inches='tight')\n",
    "        print(\"✅ Saved: validation_plots/peg_timeline.png\")\n",
    "        plt.close(fig3)\n",
    "    \n",
    "    print()\n",
    "    \n",
    "    # ========== STEP 5: VALIDATE TI ON CHOP ==========\n",
    "    print(\"STEP 5: Validating TI on choppy periods...\")\n",
    "    print(\"-\" * 70)\n",
    "    \n",
    "    ti_validation = validator.validate_ti_on_chop(\n",
    "        prices=df['close'].values,\n",
    "        chop_zone_indices=chop_indices[:10],\n",
    "        window=50\n",
    "    )\n",
    "    \n",
    "    print()\n",
    "    \n",
    "    # ========== STEP 6: VALIDATE COHERENCE ==========\n",
    "    print(\"STEP 6: Validating coherence metric...\")\n",
    "    print(\"-\" * 70)\n",
    "    \n",
    "    coherence_validation = validator.validate_coherence(\n",
    "        prices=df['close'].values,\n",
    "        sample_size=20\n",
    "    )\n",
    "    \n",
    "    print()\n",
    "    \n",
    "    # ========== STEP 7: GENERATE SUMMARY DASHBOARD ==========\n",
    "    print(\"STEP 7: Generating validation dashboard...\")\n",
    "    print(\"-\" * 70)\n",
    "    \n",
    "    validation_results = {\n",
    "        'peg': peg_validation,\n",
    "        'ti': ti_validation,\n",
    "        'coherence': coherence_validation\n",
    "    }\n",
    "    \n",
    "    fig4 = viz.plot_validation_dashboard(validation_results)\n",
    "    fig4.savefig('validation_plots/validation_dashboard.png', dpi=150, bbox_inches='tight')\n",
    "    print(\"✅ Saved: validation_plots/validation_dashboard.png\")\n",
    "    plt.close(fig4)\n",
    "    \n",
    "    print()\n",
    "    \n",
    "    # ========== FINAL SUMMARY ==========\n",
    "    print(\"=\" * 70)\n",
    "    print(\"PHASE 1 VALIDATION COMPLETE\")\n",
    "    print(\"=\" * 70)\n",
    "    print()\n",
    "    print(\"Results:\")\n",
    "    print(f\"  PEG Validation:       {'✅ PASS' if peg_validation['success'] else '❌ FAIL'}\")\n",
    "    print(f\"  TI Validation:        {'✅ PASS' if ti_validation['success'] else '❌ FAIL'}\")\n",
    "    print(f\"  Coherence Validation: {'✅ PASS' if coherence_validation['success'] else '❌ FAIL'}\")\n",
    "    print()\n",
    "    \n",
    "    all_passed = all([\n",
    "        peg_validation['success'],\n",
    "        ti_validation['success'],\n",
    "        coherence_validation['success']\n",
    "    ])\n",
    "    \n",
    "    if all_passed:\n",
    "        print(\"🎉 ALL VALIDATIONS PASSED!\")\n",
    "        print()\n",
    "        print(\"Next steps:\")\n",
    "        print(\"  1. Review validation_plots/ to visually confirm results\")\n",
    "        print(\"  2. Proceed to Phase 2: Regime Classification System\")\n",
    "        print(\"  3. Start building regime detector based on these physics metrics\")\n",
    "        print()\n",
    "    else:\n",
    "        print(\"⚠️ SOME VALIDATIONS FAILED\")\n",
    "        print()\n",
    "        print(\"Debugging steps:\")\n",
    "        print(\"  1. Review validation_plots/ to identify issues\")\n",
    "        print(\"  2. Adjust field constructor parameters:\")\n",
    "        print(\"     - Try different spatial_bins (30-70)\")\n",
    "        print(\"     - Try different smoothing_sigma (1.5-3.0)\")\n",
    "        print(\"     - Try different temporal_window (80-150)\")\n",
    "        print(\"  3. Re-run validation\")\n",
    "        print()\n",
    "    \n",
    "    # Save results to JSON\n",
    "    results_json = {\n",
    "        'peg_success': peg_validation['success'],\n",
    "        'peg_prediction_rate': peg_validation['peg_prediction_rate'],\n",
    "        'peg_avg_lead_bars': peg_validation['avg_lead_bars'],\n",
    "        'ti_success': ti_validation['success'],\n",
    "        'ti_chop_avg': ti_validation['avg_chop_ti'],\n",
    "        'ti_trend_avg': ti_validation['avg_trend_ti'],\n",
    "        'ti_ratio': ti_validation['ti_ratio'],\n",
    "        'coherence_success': coherence_validation['success'],\n",
    "        'coherence_trend': coherence_validation['trend_coherence'],\n",
    "        'coherence_range': coherence_validation['range_coherence'],\n",
    "        'all_passed': all_passed\n",
    "    }\n",
    "    \n",
    "    with open('validation_results.json', 'w') as f:\n",
    "        json.dump(results_json, f, indent=2)\n",
    "    \n",
    "    print(\"✅ Results saved to validation_results.json\")\n",
    "    print(\"=\" * 70)\n",
    "    \n",
    "    return validation_results\n",
    "\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    # Create directories\n",
    "    import os\n",
    "    os.makedirs('data/raw', exist_ok=True)\n",
    "    os.makedirs('data/processed', exist_ok=True)\n",
    "    os.makedirs('validation_plots', exist_ok=True)\n",
    "    \n",
    "    # Run validation\n",
    "    try:\n",
    "        results = phase1_complete_validation()\n",
    "    except Exception as e:\n",
    "        print(f\"\\n❌ ERROR: {e}\")\n",
    "        print(\"\\nFull traceback:\")\n",
    "        import traceback\n",
    "        traceback.print_exc()\n",
    "        sys.exit(1)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
